### ISSUE TITLE
项目从1.1.4直升3.0.0出现问题

### ISSUE THREAD

**Issue by jinangchao** [binarywang/weixin-java-cp-demo#3]
项目是几年前开发的，基于Spring MVC框架，支持配置多个自定义应用。
最近想直接升级到最新版本，一些小的接口名称改动倒是很快处理完了，但是更新后发现Spring注入失败了，这是有问题的配置文件部分，能帮我一下吗？不胜感激！
@binarywang 
V1.1.4
`<bean id="A应用WxCpService" class="me.chanjar.weixin.cp.api.WxCpServiceImpl">`
	`<property name="wxCpConfigStorage" ref="A应用WxCpConfigStorage" />`
`</bean>`
	
`<bean id="B应用PostWxCpService" class="me.chanjar.weixin.cp.api.WxCpServiceImpl">`
	`<property name="wxCpConfigStorage" ref="B应用WxCpConfigStorage" />`
`</bean>`

V3.0.0
`<bean id="A应用WxCpService" class="me.chanjar.weixin.cp.api.impl.WxCpServiceImpl">`
	`<property name="wxCpConfigStorage" ref="A应用WxCpConfigStorage" />`
`</bean>`

`<bean id="B应用PostWxCpService" class="me.chanjar.weixin.cp.api.impl.WxCpServiceImpl">`
	`<property name="wxCpConfigStorage" ref="B应用WxCpConfigStorage" />`
`</bean>`

以下是打印出来的错误：
`Caused by: java.lang.IllegalStateException: Cannot convert value of type [xxx.xxx.my.service.UserService$$EnhancerBySpringCGLIB$$c8d4e78] to required type [me.chanjar.weixin.cp.api.WxCpUserService] for property 'userService': no matching editors or conversion strategy found
	at org.springframework.beans.TypeConverterDelegate.convertIfNecessary(TypeConverterDelegate.java:287)
	at org.springframework.beans.BeanWrapperImpl.convertIfNecessary(BeanWrapperImpl.java:460)
	... 52 more`

**Comment by jinangchao** [comment]
我发现我有个Service的类名为UserService，改成别的名字就编译过了
